// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: random/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetRandomvalRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetRandomvalRequest) Reset()         { *m = QueryGetRandomvalRequest{} }
func (m *QueryGetRandomvalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRandomvalRequest) ProtoMessage()    {}
func (*QueryGetRandomvalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e7e1fe88061ff84, []int{0}
}
func (m *QueryGetRandomvalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRandomvalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRandomvalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRandomvalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRandomvalRequest.Merge(m, src)
}
func (m *QueryGetRandomvalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRandomvalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRandomvalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRandomvalRequest proto.InternalMessageInfo

func (m *QueryGetRandomvalRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetRandomvalResponse struct {
	Randomval Randomval `protobuf:"bytes,1,opt,name=randomval,proto3" json:"randomval"`
}

func (m *QueryGetRandomvalResponse) Reset()         { *m = QueryGetRandomvalResponse{} }
func (m *QueryGetRandomvalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRandomvalResponse) ProtoMessage()    {}
func (*QueryGetRandomvalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e7e1fe88061ff84, []int{1}
}
func (m *QueryGetRandomvalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRandomvalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRandomvalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRandomvalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRandomvalResponse.Merge(m, src)
}
func (m *QueryGetRandomvalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRandomvalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRandomvalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRandomvalResponse proto.InternalMessageInfo

func (m *QueryGetRandomvalResponse) GetRandomval() Randomval {
	if m != nil {
		return m.Randomval
	}
	return Randomval{}
}

type QueryAllRandomvalRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRandomvalRequest) Reset()         { *m = QueryAllRandomvalRequest{} }
func (m *QueryAllRandomvalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRandomvalRequest) ProtoMessage()    {}
func (*QueryAllRandomvalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e7e1fe88061ff84, []int{2}
}
func (m *QueryAllRandomvalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRandomvalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRandomvalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRandomvalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRandomvalRequest.Merge(m, src)
}
func (m *QueryAllRandomvalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRandomvalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRandomvalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRandomvalRequest proto.InternalMessageInfo

func (m *QueryAllRandomvalRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllRandomvalResponse struct {
	Randomval  []Randomval         `protobuf:"bytes,1,rep,name=randomval,proto3" json:"randomval"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRandomvalResponse) Reset()         { *m = QueryAllRandomvalResponse{} }
func (m *QueryAllRandomvalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRandomvalResponse) ProtoMessage()    {}
func (*QueryAllRandomvalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e7e1fe88061ff84, []int{3}
}
func (m *QueryAllRandomvalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRandomvalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRandomvalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRandomvalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRandomvalResponse.Merge(m, src)
}
func (m *QueryAllRandomvalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRandomvalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRandomvalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRandomvalResponse proto.InternalMessageInfo

func (m *QueryAllRandomvalResponse) GetRandomval() []Randomval {
	if m != nil {
		return m.Randomval
	}
	return nil
}

func (m *QueryAllRandomvalResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetRandomvalRequest)(nil), "genievot.random.random.QueryGetRandomvalRequest")
	proto.RegisterType((*QueryGetRandomvalResponse)(nil), "genievot.random.random.QueryGetRandomvalResponse")
	proto.RegisterType((*QueryAllRandomvalRequest)(nil), "genievot.random.random.QueryAllRandomvalRequest")
	proto.RegisterType((*QueryAllRandomvalResponse)(nil), "genievot.random.random.QueryAllRandomvalResponse")
}

func init() { proto.RegisterFile("random/query.proto", fileDescriptor_0e7e1fe88061ff84) }

var fileDescriptor_0e7e1fe88061ff84 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x0f, 0xd2, 0x30,
	0x14, 0xc7, 0x57, 0x14, 0x13, 0xaa, 0xa7, 0x86, 0x10, 0x24, 0x66, 0xca, 0x4c, 0x54, 0x34, 0x69,
	0x19, 0x7e, 0x02, 0x30, 0xca, 0x55, 0x77, 0xf4, 0xd6, 0x41, 0x53, 0x97, 0x8c, 0x76, 0xd0, 0x42,
	0x20, 0xc6, 0x8b, 0x9f, 0xc0, 0xc4, 0xbb, 0x17, 0x8f, 0x7e, 0x11, 0x4e, 0x86, 0xc4, 0x8b, 0x27,
	0x63, 0xc0, 0x0f, 0x62, 0x68, 0xcb, 0x80, 0x30, 0xb2, 0xe8, 0xa9, 0x8f, 0xd2, 0xff, 0x7b, 0xbf,
	0xff, 0x7b, 0x6f, 0x10, 0xcd, 0xa8, 0x18, 0xcb, 0x09, 0x99, 0xce, 0xd9, 0x6c, 0x85, 0xb3, 0x99,
	0xd4, 0x12, 0x35, 0x38, 0x13, 0x09, 0x5b, 0x48, 0x8d, 0xed, 0x9f, 0xee, 0x68, 0xdd, 0xe3, 0x52,
	0xf2, 0x94, 0x11, 0x9a, 0x25, 0x84, 0x0a, 0x21, 0x35, 0xd5, 0x89, 0x14, 0xca, 0xaa, 0x5a, 0x4f,
	0x47, 0x52, 0x4d, 0xa4, 0x22, 0x31, 0x55, 0xcc, 0xa6, 0x23, 0x8b, 0x30, 0x66, 0x9a, 0x86, 0x24,
	0xa3, 0x3c, 0x11, 0xe6, 0xb1, 0x7b, 0xdb, 0x70, 0x55, 0xed, 0xb1, 0xa0, 0xa9, 0xbb, 0xaf, 0x73,
	0xc9, 0xa5, 0x09, 0xc9, 0x3e, 0xb2, 0xb7, 0x41, 0x17, 0x36, 0xdf, 0xec, 0xf3, 0x0d, 0x99, 0x8e,
	0x0e, 0x82, 0x88, 0x4d, 0xe7, 0x4c, 0x69, 0x54, 0x87, 0xd5, 0x44, 0x8c, 0xd9, 0xb2, 0x09, 0x1e,
	0x80, 0x27, 0xb5, 0xc8, 0xfe, 0x08, 0x62, 0x78, 0xb7, 0x40, 0xa1, 0x32, 0x29, 0x14, 0x43, 0x2f,
	0x61, 0x2d, 0xaf, 0x6b, 0x64, 0xb7, 0x7b, 0x6d, 0x5c, 0x6c, 0x19, 0xe7, 0xea, 0xc1, 0xcd, 0xf5,
	0xaf, 0xfb, 0x5e, 0x74, 0x54, 0x06, 0xb1, 0xa3, 0xea, 0xa7, 0xe9, 0x05, 0xd5, 0x2b, 0x08, 0x8f,
	0x9e, 0x5d, 0x8d, 0x47, 0xd8, 0x36, 0x08, 0xef, 0x1b, 0x84, 0x6d, 0xbf, 0x5d, 0x83, 0xf0, 0x6b,
	0xca, 0x99, 0xd3, 0x46, 0x27, 0xca, 0xe0, 0x1b, 0x70, 0x46, 0xce, 0x8b, 0x14, 0x1b, 0xb9, 0xf1,
	0x7f, 0x46, 0xd0, 0xf0, 0x0c, 0xb6, 0x62, 0x60, 0x1f, 0x97, 0xc2, 0x5a, 0x86, 0x53, 0xda, 0xde,
	0xf7, 0x0a, 0xac, 0x1a, 0x5a, 0xf4, 0x15, 0xc0, 0x5a, 0x5e, 0x11, 0x75, 0xaf, 0x41, 0x5d, 0x9b,
	0x6a, 0x2b, 0xfc, 0x07, 0x85, 0x05, 0x09, 0xc2, 0x8f, 0x3f, 0xfe, 0x7c, 0xae, 0x3c, 0x43, 0x1d,
	0x72, 0x90, 0x92, 0xb3, 0x25, 0x3b, 0xee, 0x1a, 0x79, 0x6f, 0x96, 0xe4, 0x03, 0xfa, 0x02, 0xe0,
	0x9d, 0x3c, 0x51, 0x3f, 0x2d, 0x03, 0x2d, 0x18, 0x74, 0x09, 0x68, 0xd1, 0xd4, 0x82, 0x8e, 0x01,
	0x7d, 0x88, 0xda, 0xa5, 0xa0, 0x83, 0x17, 0xeb, 0xad, 0x0f, 0x36, 0x5b, 0x1f, 0xfc, 0xde, 0xfa,
	0xe0, 0xd3, 0xce, 0xf7, 0x36, 0x3b, 0xdf, 0xfb, 0xb9, 0xf3, 0xbd, 0xb7, 0x1d, 0x9e, 0xe8, 0x77,
	0xf3, 0x18, 0x8f, 0xe4, 0xe4, 0x22, 0xcd, 0xf2, 0x10, 0xe8, 0x55, 0xc6, 0x54, 0x7c, 0xcb, 0x7c,
	0x44, 0xcf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xda, 0x39, 0x1b, 0xe3, 0xea, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a randomval by index.
	Randomval(ctx context.Context, in *QueryGetRandomvalRequest, opts ...grpc.CallOption) (*QueryGetRandomvalResponse, error)
	// Queries a list of randomval items.
	RandomvalAll(ctx context.Context, in *QueryAllRandomvalRequest, opts ...grpc.CallOption) (*QueryAllRandomvalResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Randomval(ctx context.Context, in *QueryGetRandomvalRequest, opts ...grpc.CallOption) (*QueryGetRandomvalResponse, error) {
	out := new(QueryGetRandomvalResponse)
	err := c.cc.Invoke(ctx, "/genievot.random.random.Query/Randomval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RandomvalAll(ctx context.Context, in *QueryAllRandomvalRequest, opts ...grpc.CallOption) (*QueryAllRandomvalResponse, error) {
	out := new(QueryAllRandomvalResponse)
	err := c.cc.Invoke(ctx, "/genievot.random.random.Query/RandomvalAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a randomval by index.
	Randomval(context.Context, *QueryGetRandomvalRequest) (*QueryGetRandomvalResponse, error)
	// Queries a list of randomval items.
	RandomvalAll(context.Context, *QueryAllRandomvalRequest) (*QueryAllRandomvalResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Randomval(ctx context.Context, req *QueryGetRandomvalRequest) (*QueryGetRandomvalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Randomval not implemented")
}
func (*UnimplementedQueryServer) RandomvalAll(ctx context.Context, req *QueryAllRandomvalRequest) (*QueryAllRandomvalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomvalAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Randomval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRandomvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Randomval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genievot.random.random.Query/Randomval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Randomval(ctx, req.(*QueryGetRandomvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RandomvalAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRandomvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RandomvalAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genievot.random.random.Query/RandomvalAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RandomvalAll(ctx, req.(*QueryAllRandomvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "genievot.random.random.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Randomval",
			Handler:    _Query_Randomval_Handler,
		},
		{
			MethodName: "RandomvalAll",
			Handler:    _Query_RandomvalAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "random/query.proto",
}

func (m *QueryGetRandomvalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRandomvalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRandomvalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRandomvalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRandomvalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRandomvalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Randomval.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllRandomvalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRandomvalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRandomvalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRandomvalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRandomvalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRandomvalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Randomval) > 0 {
		for iNdEx := len(m.Randomval) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Randomval[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetRandomvalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRandomvalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Randomval.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllRandomvalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRandomvalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Randomval) > 0 {
		for _, e := range m.Randomval {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetRandomvalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRandomvalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRandomvalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRandomvalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRandomvalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRandomvalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Randomval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Randomval.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRandomvalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRandomvalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRandomvalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRandomvalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRandomvalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRandomvalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Randomval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Randomval = append(m.Randomval, Randomval{})
			if err := m.Randomval[len(m.Randomval)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
